### ISSUE TITLE
Status Quo

### ISSUE THREAD

**Issue by mlandermann** [ribase/sr-sendcard-7-6#1]
Hey ribase!
We use this extension in one of our projects. Now we want to upgrade the T3 core to 7.6.
Is your fork ready to use? Do you use it in production environment?
Best regards
Marc

**Comment by ribase** [comment]
Hi mlandermann
I stopped to maintain this project at the moment. There is a original Version online that works out with 7.6. 
Link: https://github.com/TYPO3-extensions/sr_sendcard
Tag: 4.0/dev-master
But its bugged as well, especially the sql statements.
Before using my extension fork just write me again, i will refactor this anyway. After that you can DL this from packagist if you desire to use composer.
Regards
Ribase

**Comment by mlandermann** [comment]
Hi ribase
Is your Tag: 4.0/dev-master still compatible to T3 Version 6.2 as well as 7.6 ?
Thanks!
Regards

**Comment by ribase** [comment]
Hi mlandermann

It should be, yes! 

Regards
